### ISSUE TITLE
GPS support?

### ISSUE THREAD

**Issue by ketilmo** [xoseperez/basicstation-docker#12]
Hi @xoseperez,

Thanks for creating this excellent basicstation implementation. Much appreciated! I have it running on an RPI with an RAK2287 hat with a GPS antenna connected using balena. I see references to GPS time in the logs, but I need help to verify if basicstation is using the physical GPS for timing or not. Hence, is GPS supported, and should it activate automatically?

**Comment by xoseperez** [comment]
Latest 2.8.4 version includes GPS support via the GPS_DEV environment variable. Set it to the GPS device.

**Comment by ketilmo** [comment]
Fantastic @xoseperez! Thank you so much for implementing this. Do you happen to know what the device path would be on a RAK2287?

**Comment by xoseperez** [comment]
Well, that depends on the host, not the concentrator. The RAK2287 (only version with GPS, mind there are versions without) exposes the GPS via UART. Depending on the host/hat it might be mapped to an available UART.

On a Raspberry Pi, the easy way is to disable console over serial with `raspi-config` but keep serial port enabled. This should map the GPS to `/dev/ttyS0`. You can also use `dev/ttyAMA0` by adding `dtoverlay=disable-bt` to the `/boot/firmware/config.txt` file. Some say it's more stable this way.
