### ISSUE TITLE
Docker container and SIGTERM/SIGKILL

### ISSUE THREAD

**Issue by jpmeijers** [xoseperez/basicstation-docker#22]
I'm still confused what exactly is going on, but the symptom that I see is the container keeps on running when I expected it to have stopped. I'll update this issue if I find more details.

When running this container in attached mode, then killing the parent, the container keeps on running.

According to the Docker docs it is because the process inside the container is running as PID1:
https://docs.docker.com/reference/cli/docker/container/run/#attach:~:text=A%20process%20running%20as%20PID%201%20inside%20a%20container
https://docs.docker.com/reference/cli/docker/container/attach/#:~:text=A%20process%20running%20as%20PID%201%20inside%20a%20container

I've seen people discuss workarounds:
https://cloud.theodo.com/en/blog/docker-processes-container#Replace_a_bash_script_process_with_exec

Perhaps this line needs to be wrapped in an `exec()`:
https://github.com/xoseperez/basicstation-docker/blob/503c877aaf078add75f77969c00f03e4852ad0b3/runner/start#L834

**Comment by xoseperez** [comment]
Hi @jpmeijers 
Interesting. I have not noticed the same issue (the container running when should be stopped) but I've noticed it keeps the "session" after a reboot. For instance, once it quits I'd expect the configuration files it creates to vanish and create them again when boot, but it does not if it reboots from an error.
Might be related, will test the workaround you suggest.

**Comment by xoseperez** [comment]
Indeed, running the station binary with an exec forces it to replace the bash script and have PID 1. I've submitted the changes but I will not yet create a new release image. You can maybe test build it locally and test.

**Comment by jpmeijers** [comment]
Yes, this solves the problem. You can clearly see from how long it takes to stop when you CTRL+C after running the container without detaching.

Before the change:
```
$ git checkout 7fe8993838d73f92ef750fc0911a257c361a5d85
$ docker compose build
$ docker compose up
...
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 1/1
 ✔ Container basicstation  Stopped                              10.2s 
canceled
```

After your change:
```
$ git checkout f051c079c370a8dd2b2278f103685fd022d45168
$ docker compose build
$ docker compose up
...
^CGracefully stopping... (press Ctrl+C again to force)
Aborting on container exit...
[+] Stopping 1/1
 ✔ Container basicstation  Stopped                              0.1s 
canceled
```

That 10 seconds it takes before the change is the Docker Engine's [default timeout](https://docs.docker.com/compose/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop) after sending SIGTERM until it SIGKILLs the container.

**Comment by xoseperez** [comment]
Pushed to last 2.8.4. version.
